# Generated by Django 6.1.1 on 2026-09-23 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mechanic', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='media_url',
            field=models.FileField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
